apiVersion: apps/v1
kind: Deployment
metadata:
  name: hf-test-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hf-test-app
  template:
    metadata:
      labels:
        app: hf-test-app
    spec:
      containers:
      - name: hf-test-app
        image: hf_app:v2.1
        ports:
        - containerPort: 8001
