# Use a minimal base image for production
FROM scratch

ARG SERVE_PORT
ENV SERVE_PORT=$SERVE_PORT

# Copy the binary from your local system to the container
COPY build/app /app

# Define the command to run your application
CMD ["./app"]
